// js/data.js
const certificates = [
  {
    id: "html-offline",
    title: "HTML & CSS Mastery",
    issuer: "Raj Computers Academy",
    category: "offline",
    platform: "Offline Training",
    date: "Jan 2024",
    hours: "40 hours",
    verified: true,
    skills: ["HTML5", "CSS3", "Responsive Design"],
    image: "https://shorturl.at/MqGVQ",
    pdf: "assets/certs/FAQs.pdf",
    // No verifyUrl → Verify button won't show
  },
  {
    id: "coursera-wpeie",
    title: "Write Professional Emails in English",
    issuer: "Georgia Institute of Technology",
    category: "coursera",
    platform: "Coursera",
    date: "Oct 24, 2025",
    hours: "14 hours",
    verified: true,
    skills: ["Writing", "Communication", "Business Writing"],
    image: "assets/certs/coursera-emails.jpg",
    pdf: "assets/certs/coursera-emails.pdf",
    verifyUrl: "https://coursera.org/verify/ABC123XYZ", // 👈 Add this
  },
  {
    id: "coursera-csf",
    title: "Customer Service Fundamentals",
    issuer: "Knowledge Accelerators",
    category: "coursera",
    platform: "Coursera",
    date: "Oct 10 2025",
    verified: true,
    skills: [
      "Customer Relationship Management",
      "Customer Engagement",
      "Customer and Client Support",
      "Technical Support and Services",
      "Help Desk Support",
      "Greeting Customers",
      "Interpersonal Communications",
      "Customer experience improvement",
      "Customer Complaint Resolution",
      "Customer Support",
      "Process Management",
      "Empathy",
    ],
    image: "https://shorturl.at/tUw8B",
    pdf: "https://shorturl.at/tUw8B",
    verifyUrl:
      "https://www.coursera.org/account/accomplishments/verify/P7S0Y9SHWP4E",
  },
  {
    id: "coursera-sp",
    title: "Successful Presentation",
    issuer: "University of Colorado Boulder",
    category: "coursera",
    platform: "Coursera",
    date: "Oct 16 2025",
    verified: true,
    skills: [
      "Public Speaking",
      "Adaptability",
      "Non-Verbal Communication",
      "Drive Engagement",
      "Communication",
      "Composure",
      "Verbal Communication Skills",
      "Storytelling",
      "Persuasive Communication",
      "Business Writing",
      "Creativity",
      "Presentations",
    ],
    image: "https://shorturl.at/j4uUk",
    pdf: "https://shorturl.at/j4uUk",
    verifyUrl:
      "https://www.coursera.org/account/accomplishments/verify/FUIWXZ70OPAT",
  },
  {
    id: "hackathon-ai",
    title: "AI Hackathon Finalist",
    issuer: "TechNova 2025",
    category: "hackathons",
    platform: "Offline Event",
    date: "Jul 2025",
    verified: true,
    skills: ["Python", "AI", "Teamwork"],
    image: "assets/certs/hackathon-ai.jpg",
    pdf: "assets/certs/hackathon-ai.pdf",
  },
];